import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import { Pool } from "pg";
import "dotenv/config";
import bcrypt from "bcryptjs";

const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
});
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

export const INITIAL_PRODUCTS = [
  {
    "id": "cha-no-sui-matcha-facial-wash-foam",
    "name": "CHA NO SUI Matcha Facial Wash Foam",
    "tagline": "Kyoto Uji Matcha soothing facial foam & pore care",
    "category": "Cleansers",
    "price": 38,
    "originalPrice": 46,
    "image": "/products/image16.png",
    "gallery": [
      "/products/image16.png"
    ],
    "description": "A foaming face wash that leaves your skin feeling moisturized with a rich, creamy lather. Formulated with Kyoto-grown Uji matcha, vitamin C, and enzymes, it cleanses while tightening and soothing pores. Ideal for mature skin struggling with pore concerns and gentle enough for delicate skin. Enjoy the refreshing scent of matcha.",
    "benefits": [
      "Kyoto grown Uji tea leaves",
      "Aromatic scent of matcha",
      "Gentle to the skin",
      "Vitamin C & enzymes"
    ],
    "ingredients": [
      "WATER",
      "GLYCERIN",
      "MYRISTIC ACID",
      "POTASSIUM HYDROXIDE",
      "STEARIC ACID",
      "LAURIC ACID",
      "PEG-75",
      "BENTONITE",
      "GLYCERYL STEARATE",
      "FRAGRANCE",
      "ETIDRONIC ACID",
      "TETRASODIUM ETIDRONATE",
      "PHENOXYETHANOL",
      "SODIUM HYDROXIDE",
      "TOCOPHEROL",
      "HYDROGENATED LECITHIN",
      "POLYQUATERNIUM-7",
      "BUTYLENE GLYCOL",
      "DIGLYCERIN",
      "ORYZA SATIVA (RICE) BRAN OIL",
      "PENTYLENE GLYCOL",
      "BEESWAX",
      "CAMELLIA SINENSIS SEED OIL",
      "CAMELLIA SINENSIS LEAF POWDER",
      "TRIETHYLHEXANOIN",
      "SQUALANE",
      "BATYL ALCOHOL",
      "OLEA EUROPAEA (OLIVE) FRUIT OIL",
      "DIPOTASSIUM GLYCYRRHIZATE",
      "DIPENTAERYTHRITYL HEXAHYDROXYSTEARATE",
      "CHOLESTERYL HYDROXYSTEARATE",
      "MACADAMIA INTEGRIFOLIA SEED OIL",
      "BISABOLOL",
      "PHYTOSTERYL/OCTYLDODECYL LAUROYL GLUTAMATE",
      "SIMMONDSIA CHINENSIS (JOJOBA) SEED OIL",
      "ROSA CANINA FRUIT OIL",
      "CAPRYLIC/CAPRIC TRIGLYCERIDE",
      "ALOE BARBADENSIS LEAF JUICE",
      "DEXTRIN",
      "GLYCERYL GLUCOSIDE",
      "CHLOROPHYLLIN-COPPER COMPLEX",
      "ARGININE",
      "CARBOMER",
      "CYCLODEXTRIN",
      "ASCORBYL TETRAISOPALMITATE",
      "ALCOHOL",
      "XANTHAN GUM",
      "LACTOSE",
      "GLYCYRRHIZA GLABRA (LICORICE) ROOT EXTRACT",
      "LIPASE",
      "CHOLESTEROL",
      "RICE FERMENT FILTRATE (SAKE)",
      "GLYCOSPHINGOLIPIDS",
      "PAPAIN",
      "COIX LACRYMA-JOBI MA-YUEN SEED EXTRACT",
      "BROMELAIN",
      "ROSMARINUS OFFICINALIS (ROSEMARY) LEAF EXTRACT",
      "MADECASSOSIDE",
      "ASIATICOSIDE",
      "ASIATIC ACID",
      "MADECASSIC ACID",
      "PRUNUS PERSICA (PEACH) LEAF EXTRACT",
      "ARNICA MONTANA FLOWER EXTRACT",
      "HYPERICUM PERFORATUM FLOWER/LEAF/STEM EXTRACT",
      "HEDERA HELIX (IVY) LEAF/STEM EXTRACT",
      "AESCULUS HIPPOCASTANUM (HORSE CHESTNUT) SEED EXTRACT",
      "HAMAMELIS VIRGINIANA (WITCH HAZEL) LEAF EXTRACT",
      "VITIS VINIFERA (GRAPE) LEAF EXTRACT",
      "CAMELLIA SINENSIS CATECHINS"
    ],
    "howToUse": "A foaming cleanser with rich bubbles that leaves the skin feeling moist after washing. Formulated with Kyoto Uji matcha, vitamin C, and enzymes to cleanse, tighten, and soothe pores. Suitable for delicate skin. Features a refreshing matcha scent.",
    "size": "120g",
    "skinType": "Normal, Sensitive, Delicate Skin",
    "rating": 4.9,
    "reviewCount": 47,
    "stock": 20,
    "isFeatured": true,
    "isBestSeller": true
  },
  {
    "id": "cha-no-sui-matcha-cleansing-gel",
    "name": "CHA NO SUI Matcha Cleansing Gel",
    "tagline": "Kyoto Uji tea leaves & enzyme deep cleansing gel",
    "category": "Cleansers",
    "price": 44,
    "originalPrice": 52,
    "image": "/products/image17.png",
    "gallery": [
      "/products/image17.png"
    ],
    "description": "A cleansing gel that effectively removes pore impurities and heavy makeup. Infused with Kyoto-grown Uji matcha, vitamin C, and enzymes, it cleanses while tightening and soothing pores. Perfect for mature skin with pore concerns and gentle enough for delicate skin. Enjoy the refreshing scent of matcha.",
    "benefits": [
      "Kyoto grown Uji tea leaves",
      "Aromatic scent of matcha",
      "Removes deep makeup",
      "Vitamin C & enzymes"
    ],
    "ingredients": [
      "WATER",
      "PEG-7 GLYCERYL COCOATE",
      "DIPROPYLENE GLYCOL",
      "BIS-ETHOXYDIGLYCOL CYCLOHEXANE 1",
      "4-DICARBOXYLATE",
      "LAURYL HYDROXYSULTAINE",
      "CARBOMER",
      "PHENOXYETHANOL",
      "FRAGRANCE",
      "METHYLPARABEN",
      "SODIUM HYDROXIDE",
      "XANTHAN GUM",
      "HYDROGENATED LECITHIN",
      "BUTYLENE GLYCOL",
      "DIGLYCERIN",
      "TOCOPHEROL",
      "PENTYLENE GLYCOL",
      "CAMELLIA SINENSIS SEED OIL",
      "CAMELLIA SINENSIS LEAF POWDER",
      "TRIETHYLHEXANOIN",
      "SQUALANE",
      "BATYL ALCOHOL",
      "OLEA EUROPAEA (OLIVE) FRUIT OIL",
      "DIPOTASSIUM GLYCYRRHIZATE",
      "DIPENTAERYTHRITYL HEXAHYDROXYSTEARATE",
      "CHOLESTERYL HYDROXYSTEARATE",
      "MACADAMIA INTEGRIFOLIA SEED OIL",
      "BISABOLOL",
      "PHYTOSTERYL/OCTYLDODECYL LAUROYL GLUTAMATE",
      "SIMMONDSIA CHINENSIS (JOJOBA) SEED OIL",
      "ROSA CANINA FRUIT OIL",
      "CAPRYLIC/CAPRIC TRIGLYCERIDE",
      "ALOE BARBADENSIS LEAF JUICE",
      "GLYCERIN",
      "DEXTRIN",
      "GLYCERYL GLUCOSIDE",
      "CHLOROPHYLLIN-COPPER COMPLEX",
      "ARGININE",
      "CYCLODEXTRIN",
      "ASCORBYL TETRAISOPALMITATE",
      "ALCOHOL",
      "ORYZA SATIVA (RICE) BRAN OIL",
      "LACTOSE",
      "GLYCYRRHIZA GLABRA (LICORICE) ROOT EXTRACT",
      "LIPASE",
      "CHOLESTEROL",
      "RICE FERMENT FILTRATE (SAKE)",
      "GLYCOSPHINGOLIPIDS",
      "PAPAIN",
      "COIX LACRYMA-JOBI MA-YUEN SEED EXTRACT",
      "ROSMARINUS OFFICINALIS (ROSEMARY) LEAF EXTRACT",
      "BROMELAIN",
      "HYPERICUM ERECTUM FLOWER/LEAF/STEM EXTRACT",
      "MADECASSOSIDE",
      "ASIATICOSIDE",
      "ASIATIC ACID",
      "MADECASSIC ACID",
      "PRUNUS PERSICA (PEACH) LEAF EXTRACT",
      "ARNICA MONTANA FLOWER EXTRACT",
      "HYPERICUM PERFORATUM FLOWER/LEAF/STEM EXTRACT",
      "HEDERA HELIX (IVY) LEAF/STEM EXTRACT",
      "AESCULUS HIPPOCASTANUM (HORSE CHESTNUT) SEED EXTRACT",
      "HAMAMELIS VIRGINIANA (WITCH HAZEL) LEAF EXTRACT",
      "VITIS VINIFERA (GRAPE) LEAF EXTRACT",
      "CAMELLIA SINENSIS CATECHINS"
    ],
    "howToUse": "A cleansing gel that smoothly removes pore impurities and heavy makeup. With Kyoto Uji matcha, vitamin C, and enzymes, it cleanses while tightening and soothing pores. Can be used on delicate skin. Features a refreshing matcha scent.",
    "size": "300ml",
    "skinType": "Mature, Sensitive, Pore-Prone Skin",
    "rating": 4.8,
    "reviewCount": 54,
    "stock": 15,
    "isFeatured": false,
    "isBestSeller": false
  },
  {
    "id": "dotbye-pore-cleansing-oil",
    "name": "dotbye Pore Cleansing Oil",
    "tagline": "Melting strawberry butter & salicylic acid pore clearing oil",
    "category": "Cleansers",
    "price": 54,
    "originalPrice": 64,
    "image": "/products/image14.png",
    "gallery": [
      "/products/image14.png",
      "/products/image26.jpg"
    ],
    "description": "Say goodbye to strawberry nose with a cleansing oil that rinses off effortlessly. Formulated with melting strawberry butter and salicylic acid to gently yet thoroughly remove makeup and pore impurities without rubbing.\nSafe to use with wet hands and eyelash extensions.\nRefreshing scent of freshly picked strawberries.",
    "benefits": [
      "Specially for strawberry nose",
      "Salicylic acid & Strawberry Butter formula",
      "Safe to use with wet hands and eyelash extensions."
    ],
    "ingredients": [
      "CETYL ETHYLHEXANOATE",
      "PEG-20 GLYCERYL TRIISOSTEARATE",
      "PEG-8 GLYCERYL ISOSTEARATE",
      "CAPRYLIC/CAPRIC TRIGLYCERIDE",
      "PROPYLENE GLYCOL DICAPRYLATE",
      "GLYCERYL BEHENATE/EICOSADIOATE",
      "WATER",
      "TOCOPHEROL",
      "PENTYLENE GLYCOL",
      "STEAROYL INULIN",
      "PHENOXYETHANOL",
      "FRAGRANCE",
      "BUTYLENE GLYCOL",
      "HYDROGENATED LECITHIN",
      "DIGLYCERIN",
      "SIMMONDSIA CHINENSIS (JOJOBA) SEED OIL",
      "TRIETHYLHEXANOIN",
      "SQUALANE",
      "BATYL ALCOHOL",
      "OLEA EUROPAEA (OLIVE) FRUIT OIL",
      "DIPOTASSIUM GLYCYRRHIZATE",
      "DIPENTAERYTHRITYL HEXAHYDROXYSTEARATE",
      "CHOLESTERYL HYDROXYSTEARATE",
      "PHYTOSTERYL/OCTYLDODECYL LAUROYL GLUTAMATE",
      "ROSA CANINA FRUIT OIL",
      "DEXTRIN",
      "GLYCERYL GLUCOSIDE",
      "ARGININE",
      "CARBOMER",
      "CYCLODEXTRIN",
      "XANTHAN GUM",
      "GLYCERIN",
      "ORYZA SATIVA (RICE) BRAN OIL",
      "LACTOSE",
      "LIPASE",
      "GLYCOSPHINGOLIPIDS",
      "PAPAIN",
      "BISABOLOL",
      "BROMELAIN",
      "ASCORBYL TETRAISOPALMITATE",
      "MACADAMIA INTEGRIFOLIA SEED OIL",
      "PERSEA GRATISSIMA (AVOCADO) OIL",
      "BUTYROSPERMUM PARKII (SHEA) BUTTER",
      "SALICYLIC ACID",
      "NIACINAMIDE",
      "MALIC ACID",
      "ASTROCARYUM MURUMURU SEED BUTTER",
      "FRAGARIA ANANASSA (STRAWBERRY) FRUIT EXTRACT"
    ],
    "howToUse": "Apply the cleansing oil to dry skin and gently massage it over your face to dissolve makeup, sunscreen, and impurities. Add a little water to emulsify the oil into a milky texture, then rinse thoroughly with lukewarm water.",
    "size": "180ml",
    "skinType": "Pore-Prone, Normal, Combination",
    "rating": 4.9,
    "reviewCount": 61,
    "stock": 35,
    "isFeatured": true,
    "isBestSeller": true
  },
  {
    "id": "kankitsu-ohji-black-peeling-gel-ex",
    "name": "KANKITSU OHJI Black Peeling Gel ex",
    "tagline": "Triple enzyme & vitamin C black peeling exfoliating gel",
    "category": "Cleansers",
    "price": 42,
    "originalPrice": 50,
    "image": "/products/image27.jpg",
    "gallery": [
      "/products/image27.jpg"
    ],
    "description": "A black peeling gel that gently lifts away stubborn dead skin cells and pore impurities. Enriched with encapsulated triple enzymes and vitamin C for a luxuriously rich feel. Leaves skin smooth, soft, and irresistibly touchable for a clearer, more refined complexion. Fresh aromalemonade scent.",
    "benefits": [
      "Gently removes dead skin and pore impurities",
      "Triple enzymes & vitamin C formula",
      "Smooth, soft, refined skin finish",
      "Fresh aromalemonade scent"
    ],
    "ingredients": [
      "WATER",
      "GLYCERIN",
      "ACRYLATES/C10-30 ALKYL ACRYLATE CROSSPOLYMER",
      "DICOCODIMONIUM CHLORIDE",
      "STEARTRIMONIUM BROMIDE",
      "ISOPROPYL ALCOHOL",
      "CHARCOAL POWDER",
      "HYDROGENATED LECITHIN",
      "MENTHOL",
      "FRAGRANCE",
      "CITRUS AURANTIUM DULCIS (ORANGE) PEEL OIL",
      "EUCALYPTUS GLOBULUS LEAF OIL",
      "ZINGIBER OFFICINALE (GINGER) ROOT OIL",
      "DIGLYCERIN",
      "CITRUS GRANDIS (GRAPEFRUIT) PEEL OIL",
      "CITRUS LIMON (LEMON) PEEL OIL",
      "CITRUS AURANTIFOLIA (LIME) OIL",
      "CITRUS NOBILIS (MANDARIN ORANGE) PEEL OIL",
      "JUNIPERUS VIRGINIANA OIL",
      "BUTYLENE GLYCOL",
      "TOCOPHEROL",
      "TRIETHYLHEXANOIN",
      "SQUALANE",
      "CHOLESTERYL HYDROXYSTEARATE",
      "BATYL ALCOHOL",
      "OLEA EUROPAEA (OLIVE) FRUIT OIL",
      "DIPOTASSIUM GLYCYRRHIZATE",
      "DIPENTAERYTHRITYL HEXAHYDROXYSTEARATE",
      "SODIUM BICARBONATE",
      "MACADAMIA INTEGRIFOLIA SEED OIL",
      "AZELAIC ACID",
      "BISABOLOL",
      "PENTYLENE GLYCOL",
      "PHYTOSTERYL/OCTYLDODECYL LAUROYL GLUTAMATE",
      "SIMMONDSIA CHINENSIS (JOJOBA) SEED OIL",
      "ROSA CANINA FRUIT OIL",
      "DEXTRIN",
      "GLYCERYL GLUCOSIDE",
      "GLYCOLIC ACID",
      "CARBOMER",
      "CYCLODEXTRIN",
      "ARGININE",
      "PHENOXYETHANOL",
      "XANTHAN GUM",
      "SALICYLIC ACID",
      "SEA SILT",
      "ORYZA SATIVA (RICE) BRAN OIL",
      "LACTOSE",
      "LIPASE",
      "GLYCOSPHINGOLIPIDS",
      "PAPAIN",
      "BROMELAIN",
      "PEG-60 HYDROGENATED CASTOR OIL",
      "CHOLESTEROL",
      "TOCOPHERYL ACETATE",
      "DIHYDROCHOLETH-20",
      "MAGNESIUM ASCORBYL PHOSPHATE",
      "METHYLPARABEN",
      "RETINYL PALMITATE",
      "ARACHIS HYPOGAEA (PEANUT) OIL",
      "PEG-100 HYDROGENATED CASTOR OIL"
    ],
    "howToUse": "First cleanse your face, then apply a small amount of the gel onto your dry face, avoiding the eye area. Gently massage the gel onto your skin in circular motions for about a minute, then rinse it off with warm water. Follow with your usual skincare routine.",
    "size": "120ml",
    "skinType": "Oily, Combination, Rough Texture",
    "rating": 4.8,
    "reviewCount": 68,
    "stock": 15,
    "isFeatured": false,
    "isBestSeller": false
  },
  {
    "id": "savon-doron-daily-esthe-face-wash-charcoal",
    "name": "SAVON DORON Daily Esthe Face Wash Charcoal",
    "tagline": "7 natural clays & bamboo charcoal aesthetic micro-foam",
    "category": "Cleansers",
    "price": 36,
    "originalPrice": 44,
    "image": "/products/image3.png",
    "gallery": [
      "/products/image3.png"
    ],
    "description": "A rich and luxurious foaming clay face wash containing 7 types of mud and enzymes. The foam of charcoal clay, which has excellent adsorptive power, firmly catches blackheads and keratin plugs in the pores, and cleans the skin, leading to a smooth skin without pores.",
    "benefits": [
      "7 Types of Mud & Enzyme",
      "Charcoal Clay Formula",
      "Firmly catches blackheads and keratin plugs in the pores",
      "Leads to a smooth skin without dirt"
    ],
    "ingredients": [
      "Water",
      "Glycerin",
      "Myristic Acid",
      "Potassium Hydroxide",
      "Stearic Acid",
      "Lauric Acid",
      "PEG-75",
      "Bentonite",
      "Glyceryl Stearate",
      "Charcoal Powder",
      "Etidronic Acid",
      "Tetrasodium Etidronate",
      "Phenoxyethanol",
      "Polyquaternium-7",
      "Tocopherol",
      "Citrus Grandis (Grapefruit) Peel Oil",
      "Citrus Aurantium Bergamia (Bergamot) Fruit Oil",
      "Rosmarinus Officinalis (Rosemary) Leaf Oil",
      "Beeswax",
      "Butylene Glycol",
      "Dextrin",
      "Illite",
      "Persea Gratissima (Avocado) Oil",
      "Argania Spinosa Kernel Oil",
      "Diatomaceous Earth",
      "Centella Asiatica Extract",
      "Honey",
      "Simmondsia Chinensis (Jojoba) Seed Oil",
      "Moroccan Lava Clay",
      "Yellow Ocher",
      "Sea Silt",
      "Sea Water",
      "Montmorillonite",
      "Yogurt Filtrate",
      "Disodium Phosphate",
      "Potassium Phosphate",
      "Papain",
      "Protease",
      "Kaolin",
      "Lipase",
      "Ascophyllum Nodosum Extract",
      "Lactobacillus/Soymilk Ferment Filtrate",
      "Zingiber Officinale (Ginger) Rhizome Extract",
      "Citrus Grandis (Grapefruit) Fruit Extract",
      "ROSA CANINA FRUIT EXTRACT"
    ],
    "howToUse": "Wet face with warm water, apply facial wash, gently massage it onto face in a circular motion, rinse thoroughly with warm water, pat dry with a clean towel. Use daily for best results.",
    "size": "120g",
    "skinType": "Oily, Acne-Prone, Clogged Pores",
    "rating": 4.9,
    "reviewCount": 75,
    "stock": 15,
    "isFeatured": false,
    "isBestSeller": true
  },
  {
    "id": "savon-doron-clay-vita-c-faical-wash",
    "name": "SAVON DORON Clay Vita C Faical Wash",
    "tagline": "White clay, vitamin C & botanical enzyme brightening wash",
    "category": "Cleansers",
    "price": 36,
    "originalPrice": 44,
    "image": "/products/image4.png",
    "gallery": [
      "/products/image4.png"
    ],
    "description": "7 types of clay, enzymes, and vitamins in a luxurious foaming clay face wash. The elastic foam of clay, which has excellent adsorption power, firmly removes blackheads and washes it to smooth skin with clear pores.",
    "benefits": [
      "Vitamin C base",
      "7 types of clay, enzymes, and vitamins",
      "Excellent adsorption power, firmly removes blackheads",
      "Washes it to smooth skin with clear pores"
    ],
    "ingredients": [
      "WATER",
      "GLYCERIN",
      "MYRISTIC ACID",
      "POTASSIUM HYDROXIDE",
      "STEARIC ACID",
      "LAURIC ACID",
      "PEG-75",
      "BENTONITE",
      "GLYCERYL STEARATE",
      "ETIDRONIC ACID",
      "TETRASODIUM ETIDRONATE",
      "PHENOXYETHANOL",
      "SODIUM HYDROXIDE",
      "POLYQUATERNIUM-7",
      "CHARCOAL POWDER",
      "FRAGRANCE",
      "TOCOPHEROL",
      "CITRUS GRANDIS (GRAPEFRUIT) PEEL OIL",
      "CYMBOPOGON SCHOENANTHUS OIL",
      "CITRUS LIMON (LEMON) PEEL OIL",
      "BEESWAX",
      "CITRUS AURANTIUM BERGAMIA (BERGAMOT) FRUIT OIL",
      "CITRUS AURANTIUM DULCIS (ORANGE) PEEL OIL",
      "BUTYLENE GLYCOL",
      "DEXTRIN",
      "ILLITE",
      "PERSEA GRATISSIMA (AVOCADO) OIL",
      "ARGANIA SPINOSA KERNEL OIL",
      "DIATOMACEOUS EARTH",
      "HONEY",
      "SIMMONDSIA CHINENSIS (JOJOBA) SEED OIL",
      "MOROCCAN LAVA CLAY",
      "SEA SILT",
      "SEA WATER",
      "MONTMORILLONITE",
      "YOGURT FILTRATE",
      "RETINYL PALMITATE",
      "DISODIUM PHOSPHATE",
      "ARACHIS HYPOGAEA (PEANUT) OIL",
      "3-GLYCERYL ASCORBATE",
      "POTASSIUM PHOSPHATE",
      "PAPAIN",
      "PROTEASE",
      "KAOLIN",
      "LIPASE",
      "ASCOPHYLLUM NODOSUM EXTRACT",
      "LACTOBACILLUS/SOYMILK FERMENT FILTRATE",
      "Zingiber Officinale (Ginger) Rhizome Extract",
      "CITRUS GRANDIS (GRAPEFRUIT) FRUIT EXTRACT",
      "ROSA CANINA FRUIT EXTRACT",
      "YELLOW OCHER"
    ],
    "howToUse": "Wet face with warm water, apply facial wash, gently massage it onto face in a circular motion, rinse thoroughly with warm water, pat dry with a clean towel. Use daily for best results.",
    "size": "120g",
    "skinType": "Dull, Sensitive, Uneven Tone",
    "rating": 4.8,
    "reviewCount": 82,
    "stock": 15,
    "isFeatured": false,
    "isBestSeller": false
  },
  {
    "id": "latte-botanical-cleanse-gel",
    "name": "LATTE BOTANICAL Cleanse Gel",
    "tagline": "4 botanical plant milks gentle makeup melt cleansing gel",
    "category": "Cleansers",
    "price": 46,
    "originalPrice": 55,
    "image": "/products/image6.png",
    "gallery": [
      "/products/image6.png",
      "/products/image10.png",
      "/products/image11.png",
      "/products/image12.png",
      "/products/image13.png",
      "/products/image21.png"
    ],
    "description": "Formulated with milk and botanical ingredients, gentle cleansing gel with shape of milk bottle. Strong cleansing power clean dirts in pores and also makeup. Moisturize and relax your skin. Herbal citrus aroma. No1 at @cosme",
    "benefits": [
      "4 types of plant milk ingredients",
      "Specializes in cleaning pores and makeup.",
      "Easily removes water-proof makeup",
      "Manna scrub"
    ],
    "ingredients": [
      "WATER",
      "PEG-7 GLYCERYL COCOATE",
      "DIPROPYLENE GLYCOL",
      "BIS-ETHOXYDIGLYCOL CYCLOHEXANE 1",
      "4-DICARBOXYLATE",
      "CARBOMER",
      "PHENOXYETHANOL",
      "LAURYL HYDROXYSULTAINE",
      "SODIUM HYDROXIDE",
      "METHYLPARABEN",
      "XANTHAN GUM",
      "AMYRIS BALSAMIFERA BARK OIL",
      "CITRUS AURANTIUM DULCIS (ORANGE) PEEL OIL",
      "PELARGONIUM GRAVEOLENS OIL",
      "CYMBOPOGON MARTINI OIL",
      "CITRUS AURANTIUM BERGAMIA (BERGAMOT) FRUIT OIL",
      "LAVANDULA ANGUSTIFOLIA (LAVENDER) OIL",
      "BUTYLENE GLYCOL",
      "PRUNUS AMYGDALUS DULCIS (SWEET ALMOND) OIL",
      "ASTROCARYUM MURUMURU SEED BUTTER",
      "PERSEA GRATISSIMA (AVOCADO) OIL",
      "LINUM USITATISSIMUM (LINSEED) SEED OIL",
      "THEOBROMA CACAO (COCOA) SEED BUTTER",
      "GLUCOMANNAN",
      "ORYZA SATIVA (RICE) STARCH",
      "SALVIA HISPANICA SEED OIL",
      "BUTYROSPERMUM PARKII (SHEA) BUTTER",
      "JASMINUM OFFICINALE (JASMINE) OIL",
      "HONEY",
      "BRASSICA OLERACEA ITALICA (BROCCOLI) SEED OIL",
      "COCOS NUCIFERA (COCONUT) OIL",
      "LACTOSE",
      "WHEY PROTEIN",
      "ASPALATHUS LINEARIS EXTRACT",
      "ROSA CANINA FRUIT EXTRACT",
      "Lactobacillus/Soymilk Ferment Filtrate",
      "EUTERPE OLERACEA FRUIT EXTRACT",
      "ROSMARINUS OFFICINALIS (ROSEMARY) LEAF EXTRACT",
      "COFFEA ARABICA (COFFEE) SEED EXTRACT",
      "EUCALYPTUS GLOBULUS LEAF EXTRACT"
    ],
    "howToUse": "First, wet your face with warm water. Take a small amount of makeup cleansing gel in your hand and massage it onto your face, including the eye area. Rinse off with water and pat your face dry. Follow with your skincare routine.",
    "size": "300ml",
    "skinType": "Dry, Sensitive, All Skin Types",
    "rating": 4.9,
    "reviewCount": 89,
    "stock": 10,
    "isFeatured": true,
    "isBestSeller": false
  },
  {
    "id": "cha-no-sui-matcha-waterproof-sunscreen-cream-spf50-pa",
    "name": "CHA NO SUI Matcha Waterproof Sunscreen Cream (SPF50+ PA++++)",
    "tagline": "SPF50+ PA++++ broad-spectrum antioxidant matcha UV shield",
    "category": "Sunscreen & UV",
    "price": 48,
    "originalPrice": 58,
    "image": "/products/image31.jpg",
    "gallery": [
      "/products/image31.jpg"
    ],
    "description": "This SPF50+ sunscreen cream combines modern UV filters with skincare-focused ingredients to provide broad-spectrum sun protection while helping maintain healthy-looking skin. Enriched with matcha extract, niacinamide, panthenol, centella asiatica, and hyaluronic acid, it helps soothe, hydrate, and support the skin barrier during daily sun exposure. Its lightweight cream texture is designed to absorb comfortably without feeling overly greasy, making it suitable for everyday face and body use. The formula also includes antioxidant-rich botanical extracts that help defend the skin against environmental stressors and signs of premature aging. Suitable for all skin types, it aims to deliver effective protection with a smooth, soft finish.",
    "benefits": [
      "SPF50+ PA++++ broad-spectrum protection against UVA & UVB rays",
      "Lightweight, non-greasy texture suitable for daily face & body use",
      "Enriched with matcha, niacinamide, and centella for soothing care & Anti-aging",
      "Waterproof formula helps maintain protection during sweat and humidity",
      "Helps hydrate, soften, and support healthy-looking skin with antioxidant-rich ingredients"
    ],
    "ingredients": [
      "WATER",
      "ETHYLHEXYL METHOXYCINNAMATE",
      "DIETHYLHEXYL SEBACATE",
      "OCTOCRYLENE",
      "DIETHYLAMINO HYDROXYBENZOYL HEXYL BENZOATE",
      "BIS-ETHYLHEXYLOXYPHENOL METHOXYPHENYL TRIAZINE",
      "PEG-8",
      "TALC",
      "C9-12 ALKANE",
      "TITANIUM DIOXIDE",
      "POLYGLYCERYL-2 STEARATE",
      "PLANKTON EXTRACT",
      "GLYCERYL STEARATE",
      "POLYGLYCERYL-4 LAURATE",
      "STEARYL ALCOHOL",
      "PHENOXYETHANOL",
      "CELLULOSE GUM",
      "POLYGLYCERYL-6 LAURATE",
      "DEXTRIN PALMITATE",
      "ETHYLHEXYLGLYCERIN",
      "FRAGRANCE",
      "AMMONIUM ACRYLOYLDIMETHYLTAURATE/VP COPOLYMER",
      "MAGNESIUM STEARATE",
      "XANTHAN GUM",
      "AMMONIUM ACRYLOYLDIMETHYLTAURATE/BEHENETH-25 METHACRYLATE CROSSPOLYMER",
      "HYDROXYPROPYL CYCLODEXTRIN",
      "ALUMINUM HYDROXIDE",
      "SODIUM HYALURONATE",
      "CAMELLIA SINENSIS SEED OIL",
      "CAMELLIA SINENSIS LEAF POWDER",
      "PANTHENOL",
      "NIACINAMIDE",
      "CENTELLA ASIATICA LEAF EXTRACT",
      "BUTYLENE GLYCOL",
      "T-BUTYL ALCOHOL",
      "PENTYLENE GLYCOL",
      "IODOPROPYNYL BUTYLCARBAMATE",
      "GLYCYRRHIZA GLABRA (LICORICE) ROOT EXTRACT",
      "CHAMOMILLA RECUTITA (MATRICARIA) FLOWER EXTRACT"
    ],
    "howToUse": "Apply evenly to clean, dry skin 15\u201320 minutes before sun exposure. Use a sufficient amount on the face and body, avoiding direct contact with the eyes. Reapply every 2 hours during prolonged sun exposure and after swimming, sweating, or towel drying. For best results, use daily as the final step of your skincare routine.",
    "size": "70ml",
    "skinType": "All Skin Types, Daily UV Barrier",
    "rating": 4.8,
    "reviewCount": 96,
    "stock": 45,
    "isFeatured": true,
    "isBestSeller": true
  },
  {
    "id": "yuiha-goshinboku-aroma-mist-hinoki-2026-winter-new",
    "name": "YUIHA Goshinboku Aroma Mist Hinoki   (2026 Winter NEW)",
    "tagline": "Sacred Japanese cypress hinoki calming aroma mist",
    "category": "Mists & Essences",
    "price": 52,
    "originalPrice": 62,
    "image": "/products/image32.jpg",
    "gallery": [
      "/products/image32.jpg"
    ],
    "description": "Calming, alcohol-free fragrance spray for body, hair, and spaces. It uses upcycled cypress essential oil from sacred \u201cGoshinboku\u201d trees at Nagaoka Tenmangu Shrine in Kyoto, supporting shrine upkeep through proceeds. Eco-friendly packaging with reduced plastic supports sustainability. Suitable as a daily personal, room, or fabric mist for relaxation.",
    "benefits": [
      "Made with natural cypress essential oil for a clean, calming woody scent inspired by nature.",
      "Alcohol-free formula that feels gentle and refreshing on both skin and hair.",
      "Multi-use mist that can be used as a body spray, hair mist, or room fragrance.",
      "Eco-friendly packaging designed with reduced plastic materials for a more sustainable lifestyle.",
      "Infused with botanical ingredients that help provide a fresh and moisturizing feel."
    ],
    "ingredients": [
      "WATER",
      "BUTYLENE GLYCOL",
      "PEG-40 HYDROGENATED CASTOR OIL",
      "SODIUM BENZOATE",
      "PHENOXYETHANOL",
      "CHAMAECYPARIS OBTUSA OIL",
      "SODIUM CITRATE",
      "EUCALYPTUS GLOBULUS LEAF OIL",
      "CUPRESSUS SEMPERVIRENS OIL",
      "MENTHA ARVENSIS LEAF OIL",
      "CITRUS GRANDIS (GRAPEFRUIT) PEEL OIL",
      "CYMBOPOGON MARTINI OIL",
      "CITRUS AURANTIUM DULCIS (ORANGE) OIL",
      "ROSMARINUS OFFICINALIS (ROSEMARY) LEAF OIL",
      "CITRIC ACID",
      "HYDROLYZED SOYBEAN EXTRACT",
      "CAMELLIA SINENSIS LEAF EXTRACT",
      "ORYZA SATIVA (RICE) LEES EXTRACT"
    ],
    "howToUse": "Shake gently before use and spray a small amount onto your skin or hair from a short distance. Reapply anytime you want a refreshing and calming fragrance throughout the day. The mist can also be lightly sprayed into rooms, on fabric, or in personal spaces to create a relaxing atmosphere. Avoid contact with eyes and do not spray directly onto sensitive areas.",
    "size": "100ml",
    "skinType": "All Skin Types, Calming & Aromatherapy",
    "rating": 4.9,
    "reviewCount": 103,
    "stock": 25,
    "isFeatured": true,
    "isBestSeller": false
  },
  {
    "id": "kankitsu-ohji-facial-peeling-gel-sp",
    "name": "KANKITSU OHJI Facial Peeling Gel SP",
    "tagline": "Citrus fruit AHA & 100x vitamin C exfoliating peeling gel",
    "category": "Cleansers",
    "price": 48,
    "originalPrice": 58,
    "image": "/products/image1.png",
    "gallery": [
      "/products/image1.png",
      "/products/image7.png",
      "/products/image8.png",
      "/products/image9.png"
    ],
    "description": "Peeling gel for men that removes dead skin cells and sebum. It leads to smooth, clear and clean skin. Contains keratin softening ingredients (AHA + BHA), vitamin C derivatives, proteins, organic citrus, and tea tree oil. Citrus scent.",
    "benefits": [
      "Peeling Gel SP,  Exfoliating Gel",
      "Removes dead skin and blackheads in the pores",
      "100 Times Penetration Type Vitamin C Derivatives",
      "CICA & Tea Tree Oil & Protein &Arginine & Taurine"
    ],
    "ingredients": [
      "WATER",
      "GLYCERIN",
      "ACRYLATES/C10-30 ALKYL ACRYLATE CROSSPOLYMER",
      "DICOCODIMONIUM CHLORIDE",
      "STEARTRIMONIUM BROMIDE",
      "ISOPROPYL ALCOHOL",
      "CITRUS AURANTIUM DULCIS (ORANGE) PEEL OIL",
      "FRAGRANCE",
      "ARGININE",
      "CENTELLA ASIATICA LEAF EXTRACT",
      "MELALEUCA ALTERNIFOLIA (TEA TREE) LEAF OIL",
      "TRISODIUM ASCORBYL PALMITATE PHOSPHATE",
      "CITRUS AURANTIUM AMARA (BITTER ORANGE) LEAF/TWIG OIL",
      "GLYCOLIC ACID",
      "TAURINE",
      "BUTYLENE GLYCOL",
      "PROPYLENE GLYCOL",
      "HYDROLYZED SOY PROTEIN",
      "PEG-40 HYDROGENATED CASTOR OIL",
      "HYPERICUM PERFORATUM EXTRACT",
      "LYSINE HCL",
      "ALANINE",
      "ARNICA MONTANA FLOWER EXTRACT",
      "HAMAMELIS VIRGINIANA (WITCH HAZEL) EXTRACT",
      "HISTIDINE HCL",
      "SERINE",
      "UREA",
      "PROLINE",
      "SALIX ALBA (WILLOW) BARK EXTRACT",
      "GLUTAMIC ACID",
      "THREONINE",
      "VALINE",
      "LEUCINE",
      "GLYCINE",
      "ALLANTOIN",
      "ISOLEUCINE",
      "PHENYLALANINE",
      "MENTHOL",
      "CITRUS GRANDIS (GRAPEFRUIT) FRUIT EXTRACT",
      "CRATAEGUS CUNEATA FRUIT EXTRACT",
      "ZIZIPHUS JUJUBA FRUIT EXTRACT",
      "PYRUS MALUS (APPLE) FRUIT EXTRACT",
      "SALICYLIC ACID",
      "CITRUS AURANTIFOLIA (LIME) JUICE",
      "CITRUS AURANTIUM DULCIS (ORANGE) JUICE",
      "CITRUS LIMON (LEMON) JUICE"
    ],
    "howToUse": "First cleanse your face, then apply a small amount of the gel onto your dry face, avoiding the eye area. Gently massage the gel onto your skin in circular motions for about a minute, then rinse it off with warm water. Follow with your usual skincare routine.",
    "size": "230ml",
    "skinType": "Rough, Sebum-Prone, Men & All Skin",
    "rating": 4.8,
    "reviewCount": 110,
    "stock": 25,
    "isFeatured": false,
    "isBestSeller": true
  },
  {
    "id": "kankitsu-ohji-facial-clear-whip-sp",
    "name": "KANKITSU OHJI Facial Clear Whip SP",
    "tagline": "CICA, tea tree & citrus clear whip sebum control foam",
    "category": "Cleansers",
    "price": 45,
    "originalPrice": 54,
    "image": "/products/image2.png",
    "gallery": [
      "/products/image2.png"
    ],
    "description": "Facial cleanser for men, comes out with foam that removes sticky sebum and dirt from pores. It leads to smooth, clean skin without unwantedshiny look. Contains vitamin C derivatives, protein, organic citrus, and tea tree oil. CItrus scent.",
    "benefits": [
      "Clear whip SP, Foam cleanser",
      "Sticky and shiny facial cleanser that comes out with foam",
      "100 Times Penetration Type Vitamin C Derivatives",
      "CICA & Tea Tree Oil & Protein &Arginine & Taurine"
    ],
    "ingredients": [
      "WATER",
      "GLYCERIN",
      "SEKKEN SOJI-K(JPN)",
      "BUTYLENE GLYCOL",
      "COCAMIDOPROPYL BETAINE",
      "POTASSIUM COCOYL GLYCINATE",
      "ARGININE COCOATE",
      "PHENOXYETHANOL",
      "PEG-40 HYDROGENATED CASTOR OIL",
      "CITRUS AURANTIUM DULCIS (ORANGE) PEEL OIL",
      "FRAGRANCE",
      "TETRASODIUM GLUTAMATE DIACETATE",
      "MENTHOL",
      "SODIUM GLYCOLATE",
      "POTASSIUM HYDROXIDE",
      "ARGININE",
      "TAURINE",
      "CENTELLA ASIATICA LEAF EXTRACT",
      "MELALEUCA ALTERNIFOLIA (TEA TREE) LEAF OIL",
      "TRISODIUM ASCORBYL PALMITATE PHOSPHATE",
      "CITRUS AURANTIUM AMARA (BITTER ORANGE) LEAF/TWIG OIL",
      "MALIC ACID"
    ],
    "howToUse": "Wet your face with warm water and dispense a small amount of foam onto your palm. Rub your hands together to create a lather, then gently massage the foam onto your face in circular motions. Rinse it off with warm water and pat your face dry.",
    "size": "360ml",
    "skinType": "Shiny, Sticky Sebum, Men & All Skin",
    "rating": 4.9,
    "reviewCount": 117,
    "stock": 30,
    "isFeatured": false,
    "isBestSeller": false
  },
  {
    "id": "kankitsu-ohji-clay-foam-sp",
    "name": "KANKITSU OHJI Clay Foam SP",
    "tagline": "Okinawa sea mud, salicylic acid & azelaic acid clay wash",
    "category": "Cleansers",
    "price": 38,
    "originalPrice": 46,
    "image": "/products/image25.jpg",
    "gallery": [
      "/products/image25.jpg"
    ],
    "description": "A clay facial cleanser with a smooth, sea-mud-like texture for a spa-like experience. Its rich, dense foam deeply absorbs pore-clogging impurities and blackheads. Now formulated with trending peeling ingredients\u2014Salicylic Acid and Azelaic Acid\u2014for enhanced clarity.\nFeatures a refreshing bergamot citrus fragrance.",
    "benefits": [
      "Dense Clay Wash with Foam",
      "Get Rid of Blackheads and Pores",
      "Okinawa Sea Mud &Salicylic Acid and Azelaic Acid & AHA",
      "Scent of Bergamot Citrus"
    ],
    "ingredients": [
      "WATER",
      "GLYCERIN",
      "MYRISTIC ACID",
      "POTASSIUM HYDROXIDE",
      "BENTONITE",
      "STEARIC ACID",
      "LAURIC ACID",
      "PEG-75",
      "CHARCOAL POWDER",
      "MENTHOL",
      "ETIDRONIC ACID",
      "TETRASODIUM ETIDRONATE",
      "GLYCERYL STEARATE",
      "PHENOXYETHANOL",
      "POLYQUATERNIUM-7",
      "CITRUS AURANTIUM DULCIS (ORANGE) PEEL OIL",
      "FRAGRANCE",
      "TOCOPHEROL",
      "SEA SILT",
      "ARGININE",
      "SODIUM BICARBONATE",
      "CENTELLA ASIATICA LEAF EXTRACT",
      "TRISODIUM ASCORBYL PALMITATE PHOSPHATE",
      "SALICYLIC ACID",
      "AZELAIC ACID",
      "TAURINE",
      "DEXTRIN",
      "PAPAIN",
      "CITRUS AURANTIUM AMARA (BITTER ORANGE) FLOWER OIL",
      "CITRUS AURANTIUM AMARA (BITTER ORANGE) LEAF/TWIG OIL",
      "MELALEUCA ALTERNIFOLIA (TEA TREE) LEAF OIL",
      "GLYCOLIC ACID"
    ],
    "howToUse": "Wet face with warm water, apply facial wash, gently massage it onto face in a circular motion, rinse thoroughly with warm water, pat dry with a clean towel. Use daily for best results.",
    "size": "120g",
    "skinType": "Clogged Pores, Blackheads, All Skin",
    "rating": 4.8,
    "reviewCount": 124,
    "stock": 35,
    "isFeatured": false,
    "isBestSeller": false
  },
  {
    "id": "reluce-skin-milk-lotion-shiny-freesia",
    "name": "RELUCE Skin Milk Lotion Shiny Freesia",
    "tagline": "Pear & shiny freesia fragrance skin milk with vitamin C",
    "category": "Creams & Balms",
    "price": 49,
    "originalPrice": 59,
    "image": "/products/image15.png",
    "gallery": [
      "/products/image15.png"
    ],
    "description": "Indulge in an all-over body milk lotion with a sophisticated fragrance that lifts your spirits. The delicate and refreshing scent of pear and freesia is paired with Vitamin C derivatives and skincare proteins. This lotion provides a melting moisture, leaving your skin radiant and clear.",
    "benefits": [
      "Fragrance Skin Milk",
      "Vitamin C derivatives and skincare proteins",
      "High moisture"
    ],
    "ingredients": [
      "WATER",
      "DIPROPYLENE GLYCOL",
      "MINERAL OIL",
      "STEARETH-13",
      "SORBITAN SESQUIOLEATE",
      "CARBOMER",
      "PHENOXYETHANOL",
      "FRAGRANCE",
      "POTASSIUM HYDROXIDE",
      "METHYLPARABEN",
      "PRUNUS AMYGDALUS DULCIS (SWEET ALMOND) OIL",
      "HYDROXYETHYLCELLULOSE",
      "HYDROLYZED SOY PROTEIN",
      "ORYZA SATIVA (RICE) STARCH",
      "NIACINAMIDE",
      "GALACTOMYCES/BETULA PLATYPHYLLA JAPONICA JUICE FERMENT FILTRATE",
      "GLYCERIN",
      "CAPRYLIC/CAPRIC TRIGLYCERIDE",
      "BUTYLENE GLYCOL",
      "3-GLYCERYL ASCORBATE",
      "HYDROLYZED RICE PROTEIN",
      "TOCOPHEROL",
      "SODIUM ASCORBATE",
      "PRUNUS AMYGDALUS DULCIS (SWEET ALMOND) PROTEIN",
      "RETINOL",
      "LACTOBACILLUS/SOYMILK FERMENT FILTRATE",
      "PEG-40 HYDROGENATED CASTOR OIL"
    ],
    "howToUse": "To use fragrance body lotion, right after a shower, before going out or to change mood apply it on slightly damp skin to lock in moisture. Massage the lotion evenly into your body, focusing on dry areas, and let it absorb fully before dressing. For best results, use daily.",
    "size": "300ml",
    "skinType": "Dry, Normal, All Over Body & Skin",
    "rating": 4.9,
    "reviewCount": 41,
    "stock": 20,
    "isFeatured": false,
    "isBestSeller": false
  },
  {
    "id": "reluce-glitter-serum-fragrance-shiny-freesia",
    "name": "ReLUCE Glitter Serum Fragrance Shiny Freesia",
    "tagline": "Sparkling glitter fragrance serum with galactomyces & vitamin C",
    "category": "Serums",
    "price": 58,
    "originalPrice": 68,
    "image": "/products/image19.jpg",
    "gallery": [
      "/products/image19.jpg"
    ],
    "description": "A serum fragrance with sparkling glitter, featuring the charming and delicate scent of Shiny Freesia. Just a quick application on your neck, d\u00e9colletage, or hair provides lasting sparkle and fragrance. Enriched with a variety of essences, including Vitamin C and Galactomyces, it helps guide your skin to a translucent, radiant complexion.",
    "benefits": [
      "Glitter Fragrance Skin Serum",
      "Vitamin C and Galactomyces",
      "For porcelain like skin",
      "Neck, d\u00e9colletage, or hair"
    ],
    "ingredients": [
      "WATER",
      "ALCOHOL",
      "BUTYLENE GLYCOL",
      "GLYCERIN",
      "PENTYLENE GLYCOL",
      "POLYSORBATE 20",
      "FRAGRANCE",
      "TREHALOSE",
      "AMMONIUM ACRYLOYLDIMETHYLTAURATE/VP COPOLYMER",
      "PHENOXYETHANOL",
      "METHYLPARABEN",
      "CALCIUM TITANIUM BOROSILICATE",
      "TITANIUM DIOXIDE",
      "CITRIC ACID",
      "TIN OXIDE",
      "GLUTATHIONE",
      "MELALEUCA ALTERNIFOLIA (TEA TREE) LEAF OIL",
      "NIACINAMIDE",
      "TRISODIUM ASCORBYL PALMITATE PHOSPHATE",
      "PANTHENOL",
      "MAGNESIUM ALUMINOMETASILICATE",
      "GALACTOMYCES/BETULA PLATYPHYLLA JAPONICA JUICE FERMENT FILTRATE",
      "CAPRYLIC/CAPRIC TRIGLYCERIDE",
      "BETA VULGARIS (BEET) ROOT EXTRACT",
      "SODIUM ASCORBATE",
      "TOCOPHEROL",
      "HABERLEA RHODOPENSIS LEAF EXTRACT",
      "RETINOL",
      "YEAST EXTRACT",
      "PEG-40 HYDROGENATED CASTOR OIL",
      "HOUTTUYNIA CORDATA EXTRACT",
      "ASIATICOSIDE",
      "ASIATIC ACID",
      "APHANOTHECE SACRUM POLYSACCHARIDES",
      "MADECASSIC ACID",
      "MADECASSOSIDE",
      "ALOE BARBADENSIS LEAF EXTRACT"
    ],
    "howToUse": "To use glitter serum, apply a small amount to clean, dry skin or over makeup, focusing on areas you want to highlight, like cheekbones or eyelids. Gently blend it in with your fingers or a brush for a sparkly, glowing finish.",
    "size": "80ml",
    "skinType": "All Skin Types, Translucent Glow",
    "rating": 4.8,
    "reviewCount": 48,
    "stock": 15,
    "isFeatured": true,
    "isBestSeller": true
  },
  {
    "id": "reluce-skin-milk-lotion-prism-lily",
    "name": "RELUCE Skin Milk Lotion Prism Lily",
    "tagline": "Niacinamide & prism lily nourishing body milk lotion",
    "category": "Creams & Balms",
    "price": 49,
    "originalPrice": 59,
    "image": "/products/image18.png",
    "gallery": [
      "/products/image18.png",
      "/products/image22.jpg",
      "/products/image28.jpg"
    ],
    "description": "A luxurious body milk lotion with a sophisticated, perfume-like fragrance that elevates your mood. It features a pristine, transparent white floral scent. Enriched with niacinamide and skincare proteins, it delivers melting moisture for plump, supple, and radiant skin.",
    "benefits": [
      "Fragrance Skin Milk",
      "Niacinamide and skincare proteins",
      "High moisture"
    ],
    "ingredients": [
      "WATER",
      "DIPROPYLENE GLYCOL",
      "MINERAL OIL",
      "STEARETH-13",
      "SORBITAN SESQUIOLEATE",
      "CARBOMER",
      "PHENOXYETHANOL",
      "FRAGRANCE",
      "POTASSIUM HYDROXIDE",
      "METHYLPARABEN",
      "PRUNUS AMYGDALUS DULCIS (SWEET ALMOND) OIL",
      "HYDROXYETHYLCELLULOSE",
      "HYDROLYZED SOY PROTEIN",
      "ORYZA SATIVA (RICE) STARCH",
      "NIACINAMIDE",
      "GALACTOMYCES/BETULA PLATYPHYLLA JAPONICA JUICE FERMENT FILTRATE",
      "GLYCERIN",
      "CAPRYLIC/CAPRIC TRIGLYCERIDE",
      "BUTYLENE GLYCOL",
      "3-GLYCERYL ASCORBATE",
      "HYDROLYZED RICE PROTEIN",
      "TOCOPHEROL",
      "SODIUM ASCORBATE",
      "PRUNUS AMYGDALUS DULCIS (SWEET ALMOND) PROTEIN",
      "RETINOL",
      "LACTOBACILLUS/SOYMILK FERMENT FILTRATE",
      "PEG-40 HYDROGENATED CASTOR OIL"
    ],
    "howToUse": "To use fragrance body lotion, right after a shower, before going out or to change mood apply it on slightly damp skin to lock in moisture. Massage the lotion evenly into your body, focusing on dry areas, and let it absorb fully before dressing. For best results, use daily.",
    "size": "300ml",
    "skinType": "Dry, Dehydrated, Body & Hands",
    "rating": 4.9,
    "reviewCount": 55,
    "stock": 20,
    "isFeatured": false,
    "isBestSeller": false
  },
  {
    "id": "reluce-glitter-serum-fragrance-prism-lily",
    "name": "ReLUCE Glitter Serum Fragrance Prism Lily",
    "tagline": "Elegant prism lily shimmering serum with niacinamide",
    "category": "Serums",
    "price": 58,
    "originalPrice": 68,
    "image": "/products/image20.jpg",
    "gallery": [
      "/products/image20.jpg"
    ],
    "description": "A serum fragrance with sparkling glitter, featuring the elegant and praiseworthy scent of Prism Lily. Just a quick application on your neck, d\u00e9colletage, or hair provides lasting sparkle and fragrance. Enriched with a variety of essences, including Retinol and Niacinamide, it helps guide your skin to a firm, youthful complexion.",
    "benefits": [
      "Glitter Fragrance Skin Serum",
      "Niacinamide and Skincare proteins",
      "For porcelain like skin",
      "Neck, d\u00e9colletage, or hair"
    ],
    "ingredients": [
      "WATER",
      "ALCOHOL",
      "BUTYLENE GLYCOL",
      "GLYCERIN",
      "PENTYLENE GLYCOL",
      "POLYSORBATE 20",
      "TREHALOSE",
      "FRAGRANCE",
      "AMMONIUM ACRYLOYLDIMETHYLTAURATE/VP COPOLYMER",
      "PHENOXYETHANOL",
      "METHYLPARABEN",
      "CALCIUM TITANIUM BOROSILICATE",
      "TITANIUM DIOXIDE",
      "CITRIC ACID",
      "TIN OXIDE",
      "GLUTATHIONE",
      "MELALEUCA ALTERNIFOLIA (TEA TREE) LEAF OIL",
      "NIACINAMIDE",
      "TRISODIUM ASCORBYL PALMITATE PHOSPHATE",
      "PANTHENOL",
      "MAGNESIUM ALUMINOMETASILICATE",
      "GALACTOMYCES/BETULA PLATYPHYLLA JAPONICA JUICE FERMENT FILTRATE",
      "CAPRYLIC/CAPRIC TRIGLYCERIDE",
      "BETA VULGARIS (BEET) ROOT EXTRACT",
      "SODIUM ASCORBATE",
      "TOCOPHEROL",
      "HABERLEA RHODOPENSIS LEAF EXTRACT",
      "RETINOL",
      "YEAST EXTRACT",
      "PEG-40 HYDROGENATED CASTOR OIL",
      "HOUTTUYNIA CORDATA EXTRACT",
      "ASIATICOSIDE",
      "ASIATIC ACID",
      "APHANOTHECE SACRUM POLYSACCHARIDES",
      "MADECASSIC ACID",
      "MADECASSOSIDE",
      "ALOE BARBADENSIS LEAF EXTRACT"
    ],
    "howToUse": "To use glitter serum, apply a small amount to clean, dry skin or over makeup, focusing on areas you want to highlight, like cheekbones or eyelids. Gently blend it in with your fingers or a brush for a sparkly, glowing finish.",
    "size": "80ml",
    "skinType": "All Skin Types, Glass Radiance",
    "rating": 4.8,
    "reviewCount": 62,
    "stock": 15,
    "isFeatured": false,
    "isBestSeller": false
  },
  {
    "id": "reluce-fragrance-ice-mist-peach-sorbet",
    "name": "ReLUCE Fragrance Ice Mist Peach Sorbet",
    "tagline": "Instant cooling ice mist with refreshing peach sorbet scent",
    "category": "Mists & Essences",
    "price": 39,
    "originalPrice": 48,
    "image": "/products/image23.jpg",
    "gallery": [
      "/products/image23.jpg",
      "/products/image24.jpg",
      "/products/image29.jpg",
      "/products/image30.jpg"
    ],
    "description": "A cooling ice mist , delivers an instant cool sensation with a beloved peach fragrance, Peach Sorbet, to refresh your mood even on hot, sweaty days. Formulated with three types of vitamin C derivatives and glutathione to promote clear, radiant-looking skin.",
    "benefits": [
      "Perfume-inspired cooling ice mist",
      "Instant cooling with Peach Sorbet scent",
      "3 vitamin C derivatives & glutathione",
      "Fresh, clear, radiant skin finish"
    ],
    "ingredients": [
      "WATER",
      "ALCOHOL",
      "PEG-40 HYDROGENATED CASTOR OIL",
      "MENTHOL",
      "FRAGRANCE",
      "GLYCERIN",
      "PHENOXYETHANOL",
      "ETHYLHEXYLGLYCERIN",
      "DIPOTASSIUM GLYCYRRHIZATE",
      "MENTHA ARVENSIS LEAF OIL",
      "ASCORBYL GLUCOSIDE",
      "ASCORBIC ACID",
      "POTASSIUM ALUM",
      "GLUTATHIONE",
      "CENTELLA ASIATICA EXTRACT",
      "ASCORBYL TETRAISOPALMITATE",
      "SODIUM BICARBONATE",
      "GALACTOMYCES/BETULA PLATYPHYLLA JAPONICA JUICE FERMENT FILTRATE",
      "BUTYLENE GLYCOL",
      "CAMELLIA SINENSIS LEAF EXTRACT"
    ],
    "howToUse": "Hold about 20 cm away and spray evenly onto the skin. Use anytime you want to cool down or refresh. Suitable for face and body.",
    "size": "80ml",
    "skinType": "All Skin Types, Instant Refreshment",
    "rating": 4.9,
    "reviewCount": 69,
    "stock": 30,
    "isFeatured": false,
    "isBestSeller": false
  },
  {
    "id": "junsuhada-medicated-japanese-peppermint-water-mist",
    "name": "JUNSUHADA Medicated Japanese Peppermint Water Mist",
    "tagline": "Medicated Hokkaido peppermint soothing barrier mist",
    "category": "Serums",
    "price": 56,
    "originalPrice": 68,
    "image": "/products/image5.png",
    "gallery": [
      "/products/image5.png"
    ],
    "description": "A medicated Japanese mist that prevents acne and rough skin. Can use for whole body and also on the mask for super refreshing feeling and odor.",
    "benefits": [
      "Japanese Peppermint Formula",
      "Helps with acne and rough skin",
      "Can use it on face, body, clothes even mask.",
      "Perfect for how and humid days."
    ],
    "ingredients": [
      "Dipotassium Glycyrrhizate",
      "\uff37\uff41\uff54\uff45\uff52",
      "Glycerin",
      "Phenoxyethanol",
      "Alcohol",
      "Yeast Extract",
      "Alcohol",
      "Ethylhexylglycerin",
      "Hakka Yu(JPN)",
      "PEG-60 Hydrogenated Castor Oil",
      "Yuukari Yu(JPN)"
    ],
    "howToUse": "Hold the mist bottle about 6-8 inches away from your face and spray 2-3 times. Keep your eyes and mouth closed. Let it dry naturally or gently pat your face with your fingertips. Use it as a refreshing mist throughout the day.",
    "size": "250ml",
    "skinType": "Acne-Prone, Heated, Sensitive Skin",
    "rating": 4.8,
    "reviewCount": 76,
    "stock": 40,
    "isFeatured": true,
    "isBestSeller": true
  }
];

async function main() {
  console.log("Starting database seeding from Website Products.xlsx...");

  // 1. Clear out old products
  console.log("Clearing existing products from database...");
  await prisma.product.deleteMany({});

  // 2. Insert new 18 products from Excel
  console.log(`Seeding ${INITIAL_PRODUCTS.length} authentic Japanese cosmetic products...`);
  for (const prod of INITIAL_PRODUCTS) {
    await prisma.product.create({
      data: {
        id: prod.id,
        name: prod.name,
        tagline: prod.tagline,
        category: prod.category,
        price: prod.price,
        originalPrice: prod.originalPrice,
        image: prod.image,
        gallery: prod.gallery,
        description: prod.description,
        benefits: prod.benefits,
        ingredients: prod.ingredients,
        howToUse: prod.howToUse,
        size: prod.size,
        skinType: prod.skinType,
        rating: prod.rating,
        reviewCount: prod.reviewCount,
        stock: prod.stock,
        isFeatured: prod.isFeatured,
        isBestSeller: prod.isBestSeller,
      },
    });
    console.log(`  ✓ Seeded product: [${prod.id}] ${prod.name}`);
  }

  // 3. Seed Demo Customer Account
  const demoEmail = "customer@niimicosmetics.com";
  const demoPassword = "Customer@Niimi2026";
  const hashedDemoPassword = await bcrypt.hash(demoPassword, 10);

  const customerDemo = await prisma.customer.upsert({
    where: { email: demoEmail },
    update: {
      name: "Elena Rostova",
      phone: "+91 98765 43210",
      address: "402 Omkar Heights, Nariman Point",
      city: "Mumbai",
      state: "Maharashtra",
      postalCode: "400021",
      country: "India",
    },
    create: {
      email: demoEmail,
      password: hashedDemoPassword,
      name: "Elena Rostova",
      phone: "+91 98765 43210",
      address: "402 Omkar Heights, Nariman Point",
      city: "Mumbai",
      state: "Maharashtra",
      postalCode: "400021",
      country: "India",
    },
  });

  // 4. Seed Representative Orders
  await prisma.order.upsert({
    where: { id: "ORD-7281" },
    update: {
      customerName: "Elena Rostova",
      customerEmail: "customer@niimicosmetics.com",
      customerPhone: "+91 98765 43210",
      customerId: customerDemo.id,
      shippingAddress: "402 Omkar Heights, Nariman Point",
      city: "Mumbai",
      state: "Maharashtra",
      postalCode: "400021",
      country: "India",
      subtotal: 92,
      shippingFee: 0,
      discount: 0,
      total: 92,
      paymentMethod: "razorpay",
      paymentStatus: "paid",
      paymentReference: "pay_ONL_7281_RZP",
      settlementStatus: "settled",
      payoutChannel: "Razorpay Instant Settlement",
      orderStatus: "delivered",
      estimatedDelivery: "2026-10-06",
    },
    create: {
      id: "ORD-7281",
      customerName: "Elena Rostova",
      customerEmail: "customer@niimicosmetics.com",
      customerPhone: "+91 98765 43210",
      customerId: customerDemo.id,
      shippingAddress: "402 Omkar Heights, Nariman Point",
      city: "Mumbai",
      state: "Maharashtra",
      postalCode: "400021",
      country: "India",
      subtotal: 92,
      shippingFee: 0,
      discount: 0,
      total: 92,
      paymentMethod: "razorpay",
      paymentStatus: "paid",
      paymentReference: "pay_ONL_7281_RZP",
      settlementStatus: "settled",
      payoutChannel: "Razorpay Instant Settlement",
      orderStatus: "delivered",
      estimatedDelivery: "2026-10-06",
      items: {
        create: [
          {
            productId: "cha-no-sui-matcha-facial-wash-foam",
            name: "CHA NO SUI Matcha Facial Wash Foam",
            price: 38,
            quantity: 1,
            image: "/products/image16.png",
            size: "120g",
          },
          {
            productId: "dotbye-pore-cleansing-oil",
            name: "dotbye Pore Cleansing Oil",
            price: 54,
            quantity: 1,
            image: "/products/image14.png",
            size: "180ml",
          },
        ],
      },
    },
  });

  await prisma.order.upsert({
    where: { id: "ORD-8392" },
    update: {
      customerName: "Aarav Mehta",
      customerEmail: "aarav.mehta@lifestyle.in",
      customerPhone: "+91 98200 11223",
      shippingAddress: "12B Sea Face Road, Worli",
      city: "Mumbai",
      state: "Maharashtra",
      postalCode: "400018",
      country: "India",
      subtotal: 104,
      shippingFee: 0,
      discount: 0,
      total: 104,
      paymentMethod: "upi",
      paymentStatus: "paid",
      paymentReference: "UPI/AXIS/9981290132/SUCCESS",
      settlementStatus: "settled",
      payoutChannel: "HDFC Current Account (...4019)",
      orderStatus: "shipped",
      estimatedDelivery: "2026-10-09",
    },
    create: {
      id: "ORD-8392",
      customerName: "Aarav Mehta",
      customerEmail: "aarav.mehta@lifestyle.in",
      customerPhone: "+91 98200 11223",
      shippingAddress: "12B Sea Face Road, Worli",
      city: "Mumbai",
      state: "Maharashtra",
      postalCode: "400018",
      country: "India",
      subtotal: 104,
      shippingFee: 0,
      discount: 0,
      total: 104,
      paymentMethod: "upi",
      paymentStatus: "paid",
      paymentReference: "UPI/AXIS/9981290132/SUCCESS",
      settlementStatus: "settled",
      payoutChannel: "HDFC Current Account (...4019)",
      orderStatus: "shipped",
      estimatedDelivery: "2026-10-09",
      items: {
        create: [
          {
            productId: "yuiha-goshinboku-aroma-mist-hinoki-2026-winter-new",
            name: "YUIHA Goshinboku Aroma Mist Hinoki (2026 Winter NEW)",
            price: 52,
            quantity: 2,
            image: "/products/image32.jpg",
            size: "100ml",
          },
        ],
      },
    },
  });

  await prisma.order.upsert({
    where: { id: "ORD-9452" },
    update: {
      customerName: "Elena Rostova",
      customerEmail: "customer@niimicosmetics.com",
      customerPhone: "+91 98765 43210",
      customerId: customerDemo.id,
      shippingAddress: "402 Omkar Heights, Nariman Point",
      city: "Mumbai",
      state: "Maharashtra",
      postalCode: "400021",
      country: "India",
      subtotal: 104,
      shippingFee: 0,
      discount: 0,
      total: 104,
      paymentMethod: "cod",
      paymentStatus: "pending",
      orderStatus: "processing",
      notes: "Evening delivery preferred",
      estimatedDelivery: "2026-10-10",
    },
    create: {
      id: "ORD-9452",
      customerName: "Elena Rostova",
      customerEmail: "customer@niimicosmetics.com",
      customerPhone: "+91 98765 43210",
      customerId: customerDemo.id,
      shippingAddress: "402 Omkar Heights, Nariman Point",
      city: "Mumbai",
      state: "Maharashtra",
      postalCode: "400021",
      country: "India",
      subtotal: 104,
      shippingFee: 0,
      discount: 0,
      total: 104,
      paymentMethod: "cod",
      paymentStatus: "pending",
      orderStatus: "processing",
      notes: "Evening delivery preferred",
      estimatedDelivery: "2026-10-10",
      items: {
        create: [
          {
            productId: "cha-no-sui-matcha-waterproof-sunscreen-cream-spf50-pa",
            name: "CHA NO SUI Matcha Waterproof Sunscreen Cream (SPF50+ PA++++)",
            price: 48,
            quantity: 1,
            image: "/products/image31.jpg",
            size: "70ml",
          },
          {
            productId: "junsuhada-medicated-japanese-peppermint-water-mist",
            name: "JUNSUHADA Medicated Japanese Peppermint Water Mist",
            price: 56,
            quantity: 1,
            image: "/products/image5.png",
            size: "250ml",
          },
        ],
      },
    },
  });

  // 5. Seed Default Admin Account
  const adminEmail = process.env.ADMIN_DEFAULT_EMAIL || "admin@niimicosmetics.com";
  const adminPassword = process.env.ADMIN_DEFAULT_PASSWORD || "Admin@Niimi2026";
  const hashedAdminPassword = await bcrypt.hash(adminPassword, 10);

  await prisma.admin.upsert({
    where: { email: adminEmail },
    update: {
      password: hashedAdminPassword,
      name: "Niimi Executive Admin",
      role: "superadmin",
    },
    create: {
      email: adminEmail,
      password: hashedAdminPassword,
      name: "Niimi Executive Admin",
      role: "superadmin",
    },
  });

  console.log(`Successfully seeded Admin account (${adminEmail}) into PostgreSQL.`);
  console.log("✓ Database seeding completed successfully!");
}

main()
  .catch((e) => {
    console.error("Seeding error:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
    await pool.end();
  });
